# Beezig GitLab CI Configuration
# Copyright (C) 2020  Beezig Team
---

image: openjdk:8-alpine

include:
- template: Security/SAST.gitlab-ci.yml

variables:
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    VERSION: 7.0.0-rc1

cache: &global_cache
  key: ${CI_COMMIT_SHA}
  paths:
     - .gradle/wrapper
     - .gradle/caches
     - build
  policy: pull

stages:
    - build
    - test
    - deploy

sast:
    needs: []
    before_script:
        - apk add git
    variables:
        SAST_DEFAULT_ANALYZERS: spotbugs
    stage: test
    cache: {}

build:
    stage: build
    before_script:
        - apk add git
    script:
        - ./gradlew build
    cache:
        <<: *global_cache
        policy: pull-push

deploy artifacts:
    needs: [build]
    stage: deploy
    image: alpine:latest
    script: # Placeholder
        - pwd
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week
    cache:
        <<: *global_cache

deploy version:
    needs: [build]
    stage: deploy
    interruptible: true
    before_script:
        - apk add openssh git jq bash coreutils curl
    script:
        - chmod go= "$DEPLOY_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - ssh-agent bash -c "ssh-add \"$DEPLOY_KEY\"; git clone git@gitlab.com:Beezig/version.git ; version/update-version.sh --module beezig --type beta --version $VERSION version/beta.json ; cd version; git add beta.json ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'Update beta version' ; git push origin master"
    only:
        refs:
            - master

trigger laby build:
    stage: deploy
    trigger: Beezig/BeezigLaby
    needs: [build]
    only:
        - master

.deployments:
    stage: deploy
    interruptible: true
    before_script:
        - apk add openssh git

deploy beta:
    extends: .deployments
    environment:
        name: beta
    script:
        - chmod go= "$DEPLOYMENTS_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - "ssh-agent sh -c \"ssh-add \\\"$DEPLOYMENTS_KEY\\\" ; git clone git@gitlab.com:Beezig/deployments.git ; mkdir -p deployments/beezig-beta || true ; cp build/libs/Beezig-*.jar \\\"deployments/beezig-beta/Beezig-$VERSION-$(git rev-list --count $(git describe --tags --abbrev=0)..HEAD)-$(git log -1 --format=%h).jar\\\" ; cd deployments ; git add . ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'deploy: Deploy Beezig Beta' ; git push origin master\""
    only:
        - master
        - rewrite-2020
    except:
        - tags

deploy release:
    extends: .deployments
    environment:
        name: release
    script:
        - chmod go= "$DEPLOYMENTS_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - "ssh-agent sh -c \"ssh-add \\\"$DEPLOYMENTS_KEY\\\" ; git clone git@gitlab.com:Beezig/deployments.git ; mkdir -p deployments/beezig-release || true ; cp build/libs/Beezig-*.jar deployments/beezig-release/Beezig-$VERSION.jar ; cd deployments ; git add . ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'deploy: Deploy Beezig Release' ; git push origin master\""
    when: manual
    only:
        - tags
...
