# Beezig GitLab CI Configuration
# Copyright (C) 2020  Beezig Team
---

image: openjdk:8-alpine

stages:
    - build
    - deploy

build:
    stage: build
    before_script:
        - apk add git
    script:
    - ./gradlew build
    artifacts:
        paths:
            - build/libs/*.jar
        expire_in: 1 week

deploy version:
    stage: deploy
    before_script:
        - apk add openssh git jq bash coreutils curl
    script:
        - chmod go= "$DEPLOY_KEY"
        - mkdir -p ~/.ssh/ || true
        - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
        - ssh-agent bash -c "ssh-add \"$DEPLOY_KEY\"; git clone git@gitlab.com:Beezig/version.git ; version/update-version.sh --module beezig --type beta --version 7.0.0 version/beta.json ; cd version; git add beta.json ; git -c 'user.name=GitLab Deploy' -c 'user.email=noreply@gitlab.com' commit -m 'Update beta version' ; git push origin master"
        - curl -X POST -F token=$BEEZIGLABY_TRIGGER -F ref=rewrite https://gitlab.com/api/v4/projects/11233515/trigger/pipeline
    only:
        refs:
            - rewrite-2020

...
