language: java
jdk:
  - oraclejdk8
install: ant compile jar
before_install:
 - mkdir libs
 - cd libs
 - wget $DOWNLOAD_LINK/'5zig.jar'
 - wget $DOWNLOAD_LINK/'netty.jar'
 - wget $DOWNLOAD_LINK/'lwjgl.jar'
 - wget $DOWNLOAD_LINK/'log4j-api.jar'
 - wget $DOWNLOAD_LINK/'log4j-core.jar'
 - wget $DOWNLOAD_LINK/'authlib.jar'
 - cd ..
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  repo: RoccoDev/deploy
  target_branch: beezig
  on:
   branch: master
   branch: experimental
