language: java
jdk:
  - oraclejdk8
install: ant compile jar
before_install:
 - mkdir libs
 - cd libs
 - wget $DOWNLOAD_LINK/'5zig.jar'
 - wget $DOWNLOAD_LINK/'netty.jar'
 - wget $DOWNLOAD_LINK/'lwjgl.jar'
 - wget $DOWNLOAD_LINK/'log4j-api.jar'
 - wget $DOWNLOAD_LINK/'log4j-core.jar'
 - wget $DOWNLOAD_LINK/'authlib.jar'
 - cd ..
before_deploy:
 - mkdir $TRAVIS_BRANCH/jar
 - mv build/jar/* $TRAVIS_BRANCH/jar/
deploy:
  - provider: pages
    skip_cleanup: true
    file: $TRAVIS_BRANCH/jar/*.jar
    file_glob: true
    github_token: $GITHUB_TOKEN 
    repo: RoccoDev/5zig-TIMV-Plugin
    target_branch: gh-pages
    on: 
     branch: master
     branch: experimental
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: $TRAVIS_BRANCH/jar/*.jar
    file_glob: true
    skip_cleanup: true
    on: 
     tags: true

